# Intro to Recommender Systems Lab

Complete the exercises below to solidify your knowledge and understanding of recommender systems.

For this lab, we are going to be putting together a user similarity based recommender system in a step-by-step fashion. Our data set contains customer grocery purchases, and we will use similar purchase behavior to inform our recommender system. Our recommender system will generate 5 recommendations for each customer based on the purchases they have made.

In [1]:
import pandas as pd
from scipy.spatial.distance import pdist, squareform

In [4]:
data = pd.read_csv('../data/customer_product_sales.csv')

In [35]:
data.head()

,CustomerID,FirstName,LastName,SalesID,ProductID,ProductName,Quantity
0,61288,Rosa,Andersen,134196,229,Bread - Hot Dog Buns,16
1,77352,Myron,Murray,6167892,229,Bread - Hot Dog Buns,20
2,40094,Susan,Stevenson,5970885,229,Bread - Hot Dog Buns,11
3,23548,Tricia,Vincent,6426954,229,Bread - Hot Dog Buns,6
4,78981,Scott,Burch,819094,229,Bread - Hot Dog Buns,20

## Step 1: Create a data frame that contains the total quantity of each product purchased by each customer.

You will need to group by CustomerID and ProductName and then sum the Quantity field.

In [19]:
cust_x_prod = data.groupby(["CustomerID","ProductName"]).sum("Quantity").reset_index()

In [20]:
cust_x_prod.head()

   CustomerID                    ProductName  SalesID  ProductID  Quantity
0          33               Apricots - Dried   172592        324         1
1          33              Assorted Desserts  5363705        219         1
2          33        Bandage - Flexible Neon  6299165        273         1
3          33  Bar Mix - Pina Colada, 355 Ml  3147536        281         1
4          33         Beans - Kidney, Canned  6507033        300         1

## Step 2: Use the `pivot_table` method to create a product by customer matrix.

The rows of the matrix should represent the products, the columns should represent the customers, and the values should be the quantities of each product purchased by each customer. You will also need to replace nulls with zeros, which you can do using the `fillna` method.

In [30]:
prod_cust = pd.pivot_table(cust_x_prod,
               index = "ProductName",
               columns = "CustomerID",
               values = "Quantity").fillna(0)
prod_cust

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97697,97753,97769,97793,97900,97928,98069,98159,98185,98200
ProductName,,,,,,,,,,,,,,,,,,,,,
Anchovy Paste - 56 G Tube,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"Appetizer - Mini Egg Roll, Shrimp",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,25.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Appetizer - Mushroom Tart,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0
Appetizer - Sausage Rolls,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,25.0,25.0,25.0,0.0,25.0,0.0
Apricots - Dried,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Yeast Dry - Fermipan,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0
Yoghurt Tubes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,0.0
"Yogurt - Blueberry, 175 Gr",0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,25.0,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0
Yogurt - French Vanilla,1.0,0.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,1.0,...,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0
Zucchini - Yellow,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Step 3: Create a customer similarity matrix using `squareform` and `pdist`. For the distance metric, choose "euclidean."

In [37]:
from scipy.spatial.distance import pdist       
from scipy.spatial.distance import squareform

In [43]:
distances = pd.DataFrame(1/(1 + squareform(pdist(prod_cust.T, 'euclidean'))), 
                         index=prod_cust.columns, columns=prod_cust.columns)

distances

CustomerID,33,200,264,356,412,464,477,639,649,669,...,97697,97753,97769,97793,97900,97928,98069,98159,98185,98200
CustomerID,,,,,,,,,,,,,,,,,,,,,
33,1.000000,0.077421,0.087047,0.081800,0.080634,0.082709,0.074573,0.083020,0.081503,0.080070,...,0.004811,0.004669,0.004412,0.005019,0.004312,0.004515,0.004583,0.004355,0.004167,0.004333
200,0.077421,1.000000,0.078448,0.076435,0.073693,0.075255,0.075956,0.076435,0.077674,0.076923,...,0.004824,0.004681,0.004431,0.005047,0.004311,0.004521,0.004614,0.004367,0.004166,0.004335
264,0.087047,0.078448,1.000000,0.080070,0.081800,0.080350,0.076923,0.080634,0.082100,0.078448,...,0.004822,0.004674,0.004416,0.005035,0.004322,0.004543,0.004595,0.004365,0.004179,0.004333
356,0.081800,0.076435,0.080070,1.000000,0.076435,0.078187,0.075025,0.082403,0.077171,0.075956,...,0.004816,0.004671,0.004416,0.005038,0.004310,0.004526,0.004578,0.004365,0.004175,0.004339
412,0.080634,0.073693,0.081800,0.076435,1.000000,0.078711,0.075025,0.082403,0.078187,0.078448,...,0.004810,0.004702,0.004414,0.005034,0.004318,0.004530,0.004578,0.004367,0.004177,0.004349
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97928,0.004515,0.004521,0.004543,0.004526,0.004530,0.004533,0.004534,0.004526,0.004528,0.004523,...,0.003509,0.003509,0.003300,0.003653,0.003579,1.000000,0.003638,0.003418,0.003255,0.003245
98069,0.004583,0.004614,0.004595,0.004578,0.004578,0.004578,0.004589,0.004581,0.004585,0.004592,...,0.003509,0.003509,0.003369,0.003509,0.003496,0.003638,1.000000,0.003469,0.003345,0.003381
98159,0.004355,0.004367,0.004365,0.004365,0.004367,0.004363,0.004366,0.004363,0.004369,0.004365,...,0.003509,0.003565,0.003322,0.003431,0.003322,0.003418,0.003469,1.000000,0.003277,0.003266
98185,0.004167,0.004166,0.004179,0.004175,0.004177,0.004167,0.004168,0.004176,0.004172,0.004161,...,0.003311,0.003162,0.003255,0.003406,0.003172,0.003255,0.003345,0.003277,1.000000,0.003288
98200,0.004333,0.004335,0.004333,0.004339,0.004349,0.004347,0.004338,0.004335,0.004329,0.004347,...,0.003418,0.003345,0.003381,0.003444,0.003288,0.003245,0.003381,0.003266,0.003288,1.000000

## Step 4: Check your results by generating a list of the top 5 most similar customers for a specific CustomerID.

In [48]:
similarities = distances[33].sort_values(ascending=False)[1:].head(5)
similarities

CustomerID
264     0.087047
3535    0.087047
3317    0.087047
2503    0.085983
3305    0.085638
Name: 33, dtype: float64

## Step 5: From the data frame you created in Step 1, select the records for the list of similar CustomerIDs you obtained in Step 4.

In [54]:
simi_df = cust_x_prod[cust_x_prod["CustomerID"].isin(similarities.index)]
simi_df

      CustomerID                     ProductName  SalesID  ProductID  Quantity
131          264               Apricots - Halves  3730301        278         1
132          264                  Apricots Fresh  5035449        158         1
133          264      Bacardi Breezer - Tropical   756802         49         1
134          264                   Bagel - Plain  6728381        262         1
135          264                 Banana - Leaves  6298459        271         1
...          ...                             ...      ...        ...       ...
3003        3535             Tray - 16in Rnd Blk  6122047        166         1
3004        3535                     Wanton Wrap  2643670        253         1
3005        3535   Wine - Blue Nun Qualitatswein  3314104        269         1
3006        3535  Wine - Magnotta, Merlot Sr Vqa  6563480        192         1
3007        3535                   Yoghurt Tubes  2723180        179         1

[270 rows x 5 columns]

## Step 6: Aggregate those customer purchase records by ProductName, sum the Quantity field, and then rank them in descending order by quantity.

This will give you the total number of each product purchased by the 5 most similar customers to the customer you selected in order from most purchased to least.

In [68]:
simi_products = simi_df.groupby("ProductName")[["ProductName","Quantity"]].sum("Quantity").sort_values(ascending=False, by="Quantity")
simi_products.head()

                               Quantity
ProductName
Butter - Unsalted                     3
Wine - Ej Gallo Sierra Valley         3
Towels - Paper / Kraft                3
Soup - Campbells Bean Medley          3
Wine - Blue Nun Qualitatswein         3

## Step 7: Filter the list for products that the chosen customer has not yet purchased and then recommend the top 5 products with the highest quantities that are left.

- Merge the ranked products data frame with the customer product matrix on the ProductName field.
- Filter for records where the chosen customer has not purchased the product.
- Show the top 5 results.

In [85]:
cust_33 = cust_x_prod[cust_x_prod["CustomerID"]==33][["ProductName","Quantity"]]
rec_prod = cust_33.merge(simi_products,on="ProductName",how="outer").sort_values(ascending=False, by="Quantity_y")
rec_prod = rec_prod[rec_prod["Quantity_x"].isna()][["ProductName","Quantity_y"]].head()
rec_prod

                      ProductName  Quantity_y
59              Butter - Unsalted         3.0
62  Wine - Blue Nun Qualitatswein         3.0
61   Soup - Campbells Bean Medley         3.0
60  Wine - Ej Gallo Sierra Valley         3.0
78          Knife Plastic - White         2.0

## Step 8: Now that we have generated product recommendations for a single user, put the pieces together and iterate over a list of all CustomerIDs.

- Create an empty dictionary that will hold the recommendations for all customers.
- Create a list of unique CustomerIDs to iterate over.
- Iterate over the customer list performing steps 4 through 7 for each and appending the results of each iteration to the dictionary you created.

In [93]:
cust_lst = list(prod_cust.columns)
recommendations = []

for i in cust_lst:
    similarities = distances[i].sort_values(ascending=False)[1:].head(5)
    simi_df = cust_x_prod[cust_x_prod["CustomerID"].isin(similarities.index)]
    simi_products = simi_df.groupby("ProductName")[["ProductName","Quantity"]].sum("Quantity").sort_values(ascending=False, by="Quantity")
    customer = cust_x_prod[cust_x_prod["CustomerID"]==i][["ProductName","Quantity"]]
    rec_prod = customer.merge(simi_products,on="ProductName",how="outer").sort_values(ascending=False, by="Quantity_y")
    rec_prod = rec_prod[rec_prod["Quantity_x"].isna()][["ProductName","Quantity_y"]].head()
    rec_prod = list(rec_prod["ProductName"])
    final_rec = {"CustomerID":i,"Rec. product 1":rec_prod[0],"Rec. product 2":rec_prod[1],
                "Rec. product 3":rec_prod[2],"Rec. product 4":rec_prod[3],
                "Rec. product 5":rec_prod[4]}
    recommendations.append(final_rec)

##  Step 9: Store the results in a Pandas data frame. The data frame should a column for Customer ID and then a column for each of the 5 product recommendations for each customer.

In [94]:
pd.DataFrame(recommendations)

,CustomerID,Rec. product 1,Rec. product 2,Rec. product 3,Rec. product 4,Rec. product 5
0,33,Butter - Unsalted,Wine - Blue Nun Qualitatswein,Soup - Campbells Bean Medley,Wine - Ej Gallo Sierra Valley,Knife Plastic - White
1,200,Soup - Campbells Bean Medley,Wanton Wrap,Pork - Kidney,Bay Leaf,Muffin - Carrot Individual Wrap
2,264,Fondant - Icing,"Fish - Scallops, Cold Smoked","Veal - Inside, Choice",Bread - Italian Roll With Herbs,Wine - Two Oceans Cabernet
3,356,"Veal - Inside, Choice",Lamb - Ground,Pomello,Butter - Unsalted,"Tart Shells - Sweet, 4"
4,412,Wine - Blue Nun Qualitatswein,"Sauce - Gravy, Au Jus, Mix",Cheese - Cambozola,"Pepper - Black, Whole",Soup - Campbells Bean Medley
...,...,...,...,...,...,...
995,97928,"Soup - Campbells, Lentil","Cheese - Brie,danish",Pants Custom Dry Clean,Wiberg Super Cure,Shrimp - 31/40
996,98069,Skirt - 29 Foot,Beans - Kidney White,Milk - 1%,Cheese - Taleggio D.o.p.,Yoghurt Tubes
997,98159,"Lamb - Whole, Fresh",Bread - Raisin Walnut Oval,Chips Potato Salt Vinegar 43g,Tea - English Breakfast,Curry Paste - Madras
998,98185,Pernod,Crackers - Trio,Tea - Jasmin Green,"Peas - Pigeon, Dry",Cream Of Tartar
999,98200,Beans - Wax,Sherry - Dry,Pork - Hock And Feet Attached,Pears - Bosc,"Soup - Campbells, Cream Of"

## Step 10: Change the distance metric used in Step 3 to something other than euclidean (correlation, cityblock, consine, jaccard, etc.). Regenerate the recommendations for all customers and note the differences.

In [95]:
#funcion para generar recomendaciones con cualquier metrica
def make_recommendations(distances):
    cust_lst = list(prod_cust.columns)
    recommendations = []

    for i in cust_lst:
        similarities = distances[i].sort_values(ascending=False)[1:].head(5)
        simi_df = cust_x_prod[cust_x_prod["CustomerID"].isin(similarities.index)]
        simi_products = simi_df.groupby("ProductName")[["ProductName","Quantity"]].sum("Quantity").sort_values(ascending=False, by="Quantity")
        customer = cust_x_prod[cust_x_prod["CustomerID"]==i][["ProductName","Quantity"]]
        rec_prod = customer.merge(simi_products,on="ProductName",how="outer").sort_values(ascending=False, by="Quantity_y")
        rec_prod = rec_prod[rec_prod["Quantity_x"].isna()][["ProductName","Quantity_y"]].head()
        rec_prod = list(rec_prod["ProductName"])
        final_rec = {"CustomerID":i,"Rec. product 1":rec_prod[0],"Rec. product 2":rec_prod[1],
                    "Rec. product 3":rec_prod[2],"Rec. product 4":rec_prod[3],
                    "Rec. product 5":rec_prod[4]}
        recommendations.append(final_rec)

    return pd.DataFrame(recommendations)

In [97]:
# metrica "correlation"
distances = pd.DataFrame(1/(1 + squareform(pdist(prod_cust.T, 'correlation'))), 
                         index=prod_cust.columns, columns=prod_cust.columns)

make_recommendations(distances)

,CustomerID,Rec. product 1,Rec. product 2,Rec. product 3,Rec. product 4,Rec. product 5
0,33,Knife Plastic - White,Muffin - Zero Transfat,Banana Turning,Crush - Cream Soda,Veal - Osso Bucco
1,200,Otomegusa Dashi Konbu,Milk Powder,Potatoes - Idaho 100 Count,Crackers - Trio,Pail With Metal Handle 16l White
2,264,"Water - Mineral, Natural",Wine - Toasted Head,Snapple - Iced Tea Peach,Hersey Shakes,Pickerel - Fillets
3,356,Cheese - Taleggio D.o.p.,"Coconut - Shredded, Sweet",Ocean Spray - Kiwi Strawberry,Cheese - Cheddarsliced,Olives - Kalamata
4,412,Cake - Mini Cheesecake,Butter - Unsalted,"Salmon - Atlantic, Skin On",Wine - Hardys Bankside Shiraz,"Beans - Kidney, Red Dry"
...,...,...,...,...,...,...
995,97928,Lettuce - Treviso,"Yogurt - Blueberry, 175 Gr",Bread - Calabrese Baguette,Extract - Lemon,Coffee - Irish Cream
996,98069,Veal - Inside,"Wine - Red, Colio Cabernet",Soupfoamcont12oz 112con,Sprouts - Baby Pea Tendrils,Peas - Frozen
997,98159,"Water, Tap",Bananas,Wine - Redchard Merritt,Cumin - Whole,Chocolate - Compound Coating
998,98185,Cheese - Taleggio D.o.p.,Squid U5 - Thailand,"Peas - Pigeon, Dry",Salmon Steak - Cohoe 8 Oz,"Sole - Dover, Whole, Fresh"
999,98200,Juice - Orange,Pork - Hock And Feet Attached,Longos - Grilled Chicken With,Apricots - Dried,Carbonated Water - Cherry

In [98]:
# metrica "cityblock"
distances = pd.DataFrame(1/(1 + squareform(pdist(prod_cust.T, 'cityblock'))), 
                         index=prod_cust.columns, columns=prod_cust.columns)

make_recommendations(distances)

,CustomerID,Rec. product 1,Rec. product 2,Rec. product 3,Rec. product 4,Rec. product 5
0,33,Wine - Ej Gallo Sierra Valley,"Oranges - Navel, 72",Bay Leaf,Wine - Charddonnay Errazuriz,Chocolate - Dark
1,200,Pomello,Soup - Campbells Bean Medley,Bay Leaf,Pork - Kidney,Muffin - Carrot Individual Wrap
2,264,Wine - Two Oceans Cabernet,Bread - Italian Roll With Herbs,"Veal - Inside, Choice",Pork - Kidney,Black Currants
3,356,Butter - Unsalted,"Veal - Inside, Choice","Beets - Candy Cane, Organic","Nut - Chestnuts, Whole",Beans - Wax
4,412,Wine - Blue Nun Qualitatswein,Table Cloth 81x81 White,Soup - Campbells Bean Medley,Butter - Unsalted,"Pepper - Black, Whole"
...,...,...,...,...,...,...
995,97928,Wine - Chardonnay South,Raspberries - Fresh,Butter - Unsalted,Scallop - St. Jaques,Otomegusa Dashi Konbu
996,98069,Wine - Chardonnay South,Bar - Granola Trail Mix Fruit Nut,Pork - Hock And Feet Attached,"Rum - Coconut, Malibu",Sprouts - Baby Pea Tendrils
997,98159,Knife Plastic - White,Sherry - Dry,Bandage - Fexible 1x3,"Wine - Magnotta, Merlot Sr Vqa",Soup - Campbells Bean Medley
998,98185,Knife Plastic - White,Beef - Montreal Smoked Brisket,Ice Cream Bar - Hageen Daz To,Pork - Kidney,Lamb - Ground
999,98200,Wine - Blue Nun Qualitatswein,Foam Dinner Plate,"Wine - Magnotta, Merlot Sr Vqa",Knife Plastic - White,Soup - Campbells Tomato Ravioli

In [100]:
# metrica "cosine"
distances = pd.DataFrame(1/(1 + squareform(pdist(prod_cust.T, 'cosine'))), 
                         index=prod_cust.columns, columns=prod_cust.columns)

make_recommendations(distances)

,CustomerID,Rec. product 1,Rec. product 2,Rec. product 3,Rec. product 4,Rec. product 5
0,33,Knife Plastic - White,"Soup - Campbells, Beef Barley",Onions - Cippolini,Tea - Herbal Sweet Dreams,Banana Turning
1,200,Longos - Grilled Salmon With Bbq,Snapple Lemon Tea,General Purpose Trigger,Tomatoes Tear Drop,"Thyme - Lemon, Fresh"
2,264,Pickerel - Fillets,"Water - Mineral, Natural",Snapple - Iced Tea Peach,Wine - Ej Gallo Sierra Valley,French Pastry - Mini Chocolate
3,356,Bread - English Muffin,Olive - Spread Tapenade,Bagel - Plain,Pork - Hock And Feet Attached,Wiberg Super Cure
4,412,"Salsify, Organic",Durian Fruit,Wine - Hardys Bankside Shiraz,Bread - Raisin Walnut Oval,Sea Bass - Whole
...,...,...,...,...,...,...
995,97928,"Spoon - Soup, Plastic",Beef - Montreal Smoked Brisket,Blackberries,Cheese Cloth No 100,Cake - Mini Cheesecake
996,98069,Sprouts - Baby Pea Tendrils,Juice - Orange,Muffin Batt - Blueberry Passion,Beer - Original Organic Lager,"Nut - Chestnuts, Whole"
997,98159,"Water, Tap",Bananas,Wine - Redchard Merritt,Cumin - Whole,Chocolate - Compound Coating
998,98185,"Peas - Pigeon, Dry",Cheese - Taleggio D.o.p.,Squid U5 - Thailand,"Cheese - Brie, Triple Creme",Pernod
999,98200,Cheese - Cheddarsliced,Cheese - Cottage Cheese,Wine - Toasted Head,Island Oasis - Mango Daiquiri,Jolt Cola - Electric Blue

In [101]:
# metrica "jaccard"
distances = pd.DataFrame(1/(1 + squareform(pdist(prod_cust.T, 'jaccard'))), 
                         index=prod_cust.columns, columns=prod_cust.columns)

make_recommendations(distances)

,CustomerID,Rec. product 1,Rec. product 2,Rec. product 3,Rec. product 4,Rec. product 5
0,33,Loquat,Blueberries,Milk - 2%,Muffin Mix - Blueberry,"Cheese - Brie, Triple Creme"
1,200,Muffin - Carrot Individual Wrap,Pomello,"Beans - Kidney, Canned",Pork - Kidney,Table Cloth 81x81 White
2,264,Sauce - Demi Glace,Flavouring - Orange,Wine - Two Oceans Cabernet,"Lamb - Pieces, Diced",Chocolate - Compound Coating
3,356,"Veal - Inside, Choice",Lettuce - Spring Mix,"Pepper - Black, Whole","Tart Shells - Sweet, 4",Beef - Inside Round
4,412,Cumin - Whole,Watercress,Wine - Chablis 2003 Champs,Veal - Sweetbread,"Pepper - Black, Whole"
...,...,...,...,...,...,...
995,97928,Tray - 16in Rnd Blk,Pernod,Pastry - Choclate Baked,Sage - Ground,Cocoa Butter
996,98069,Spinach - Baby,Cheese - Parmesan Cubes,Beef - Ground Medium,Tea - Jasmin Green,Bread - French Baquette
997,98159,Chocolate - Compound Coating,Apricots - Halves,Mustard Prepared,Sponge Cake Mix - Chocolate,Bouq All Italian - Primerba
998,98185,Soup V8 Roasted Red Pepper,Coffee - Irish Cream,Crab - Imitation Flakes,Grapes - Red,Garbage Bags - Clear
999,98200,Muffin - Carrot Individual Wrap,Mussels - Cultivated,Veal - Slab Bacon,Beef - Top Sirloin,Isomalt