# Challenge 1

In this challenge you will be working on **pokemons**. You will answer a series of questions in order to practice dataframe calculation, aggregation, and transformation.

![Pokemon](pokemon.jpg)

Follow the instructions below and enter your code.

### Import all required libraries

In [1]:
# import libraries
import pandas as pd

### Import data set

Import data set `Pokemon.csv` from the `your-code` directory of this lab. Read the data into a dataframe called `pokemon`.

*Data set attributed to [Alberto Barradas](https://www.kaggle.com/abcsds/pokemon/)*

In [15]:
# import data set
pokemon = pd.read_csv('Pokemon.csv', index_col='#')

### Print first 10 rows of `pokemon`

In [16]:
# enter your code here
pokemon[:10]

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

When you look at a data set, you often wonder what each column means. Some open-source data sets provide descriptions of the data set. In many cases, data descriptions are extremely useful for data analysts to perform work efficiently and successfully.

For the `Pokemon.csv` data set, fortunately, the owner provided descriptions which you can see [here](https://www.kaggle.com/abcsds/pokemon/home). For your convenience, we are including the descriptions below. Read the descriptions and understand what each column means. This knowledge is helpful in your work with the data.

| Column | Description |
| --- | --- |
| # | ID for each pokemon |
| Name | Name of each pokemon |
| Type 1 | Each pokemon has a type, this determines weakness/resistance to attacks |
| Type 2 | Some pokemon are dual type and have 2 |
| Total | A general guide to how strong a pokemon is |
| HP | Hit points, or health, defines how much damage a pokemon can withstand before fainting |
| Attack | The base modifier for normal attacks (eg. Scratch, Punch) |
| Defense | The base damage resistance against normal attacks |
| SP Atk | Special attack, the base modifier for special attacks (e.g. fire blast, bubble beam) |
| SP Def | The base damage resistance against special attacks |
| Speed | Determines which pokemon attacks first each round |
| Generation | Number of generation |
| Legendary | True if Legendary Pokemon False if not |

### Obtain the distinct values across `Type 1` and `Type 2`

Exctract all the values in `Type 1` and `Type 2`. Then create an array containing the distinct values across both fields.

In [17]:
# enter your code here
types= [pokemon['Type 1'],pokemon['Type 2']]

### Cleanup `Name` that contain "Mega"

If you have checked out the pokemon names carefully enough, you should have found there are junk texts in the pokemon names which contain "Mega". We want to clean up the pokemon names. For instance, "VenusaurMega Venusaur" should be "Mega Venusaur", and "CharizardMega Charizard X" should be "Mega Charizard X".

In [18]:
# enter your code here
name_clean=[]
for e in pokemon.Name:
    if 'Mega' in e:
        aux=e.split('Mega')
        res='Mega'+aux[1]
        name_clean.append(res)
    else:
        name_clean.append(e)
pokemon['Name']=name_clean
# test transformed data
pokemon.head(10)

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
6,Mega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
6,Mega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

### Create a new column called `A/D Ratio` whose value equals to `Attack` devided by `Defense`

For instance, if a pokemon has the Attack score 49 and Defense score 49, the corresponding `A/D Ratio` is 49/49=1.

In [19]:
# enter your code here
pokemon['A/D Ratio'] = pokemon.Attack/pokemon.Defense

### Identify the pokemon with the highest `A/D Ratio`

In [26]:
# enter your code here
pokemon[pokemon['A/D Ratio'] == pokemon['A/D Ratio'].max()]

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
#,,,,,,,,,,,,,
386,DeoxysAttack Forme,Psychic,NaN,600,50,180,20,180,20,150,3,True,9.0

### Identify the pokemon with the lowest A/D Ratio

In [27]:
# enter your code here
pokemon[pokemon['A/D Ratio'] == pokemon['A/D Ratio'].min()]

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
#,,,,,,,,,,,,,
213,Shuckle,Bug,Rock,505,20,10,230,10,230,5,2,False,0.043478

### Create a new column called `Combo Type` whose value combines `Type 1` and `Type 2`.

Rules:

* If both `Type 1` and `Type 2` have valid values, the `Combo Type` value should contain both values in the form of `<Type 1> <Type 2>`. For example, if `Type 1` value is `Grass` and `Type 2` value is `Poison`, `Combo Type` will be `Grass-Poison`.

* If `Type 1` has valid value but `Type 2` is not, `Combo Type` will be the same as `Type 1`. For example, if `Type 1` is `Fire` whereas `Type 2` is `NaN`, `Combo Type` will be `Fire`.

In [35]:
# enter your code here
pokemon['Type 2'] = pokemon['Type 2'].fillna('')
pokemon['Combo Type'] = pokemon['Type 1'] +' '+pokemon['Type 2']
pokemon.sample(10)

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
#,,,,,,,,,,,,,,
678,MeowsticFemale,Psychic,,466,74,48,76,83,81,104,6,False,0.631579,Psychic
352,Kecleon,Normal,,440,60,90,70,60,120,40,3,False,1.285714,Normal
428,Lopunny,Normal,,480,65,76,84,54,96,105,4,False,0.904762,Normal
443,Gible,Dragon,Ground,300,58,70,45,40,45,42,4,False,1.555556,Dragon Ground
323,Mega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False,1.200000,Fire Ground
581,Swanna,Water,Flying,473,75,87,63,87,63,98,5,False,1.380952,Water Flying
127,Mega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False,1.291667,Bug Flying
178,Xatu,Psychic,Flying,470,65,75,70,95,70,95,2,False,1.071429,Psychic Flying
24,Arbok,Poison,,438,60,85,69,65,79,80,1,False,1.231884,Poison
286,Breloom,Grass,Fighting,460,60,130,80,60,60,70,3,False,1.625000,Grass Fighting

### Identify the pokemons whose `A/D Ratio` are among the top 5

In [46]:
# enter your code here
strongest = pokemon.sort_values(by=['A/D Ratio'],ascending=False)[0:5]
strongest

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
#,,,,,,,,,,,,,,
386,DeoxysAttack Forme,Psychic,,600,50,180,20,180,20,150,3,True,9.000,Psychic
318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500,Water Dark
15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750,Bug Poison
408,Cranidos,Rock,,350,67,125,40,30,30,58,4,False,3.125,Rock
319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000,Water Dark

### For the 5 pokemons printed above, aggregate `Combo Type` and use a list to store the unique values.

Your end product is a list containing the distinct `Combo Type` values of the 5 pokemons with the highest `A/D Ratio`.

In [49]:
# enter your code here
poke_top = list(strongest['Combo Type'].unique())
poke_top

['Psychic ', 'Water Dark', 'Bug Poison', 'Rock ']

### For each of the `Combo Type` values obtained from the previous question, calculate the mean scores of all numeric fields across all pokemons.

Your output should look like below:

![Aggregate](aggregated-mean.png)

In [51]:
# enter your code here
strongest.groupby('Combo Type').mean()

,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
Combo Type,,,,,,,,,,
Bug Poison,495.0,65.0,150.0,40.0,15.0,80.0,145.0,1.0,False,3.750
Psychic,600.0,50.0,180.0,20.0,180.0,20.0,150.0,3.0,True,9.000
Rock,350.0,67.0,125.0,40.0,30.0,30.0,58.0,4.0,False,3.125
Water Dark,382.5,57.5,105.0,30.0,80.0,30.0,80.0,3.0,False,3.750